name: Check Commit Syntax

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check commit syntax
        uses: adityaa30/check-commit@master