name: Python Syntax Check Test

on: [push, pull_request]

jobs:
  syntax-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test - Syntax check of all py files
        run: ./scripts/python-syntax.sh
